import io
import os
from typing import Dict, Tuple, Any, Type
from rllm.environments.base.base_env import BaseEnv
from rllm.environments.jericho.raw_env import JerichoEnv
from rllm.misc import colorful_print
import threading
import time
import datetime
from types import SimpleNamespace

JERICHO_MAX_SCORES = {
    "905": 1,
    "acorncourt": 30,
    "advent": 350,       # Note: Starts with score 36
    "adventureland": 100,
    "afflicted": 75,
    "anchor": 100,       # Anchorhead
    "awaken": 50,
    "balances": 51,
    "deephome": 300,
    "detective": 360,
    "dragon": 25,
    "enchanter": 400,
    "gold": 100,
    "inhumane": 90,
    "jewel": 90,
    "karn": 170,
    "library": 30,
    "ludicorp": 150,
    "moonlit": 1,
    "omniquest": 50,
    "pentari": 70,
    "reverb": 50,
    "snacktime": 50,
    "sorcerer": 400,
    "spellbrkr": 600,
    "spirit": 250,
    "temple": 35,
    "tryst205": 350,
    "yomomma": 35,
    "zenon": 20,
    "zork1": 350,
    "zork3": 7,
    "ztuu": 100          # Zork: The Undiscovered Underground
}
class StateNode:
    def __init__(self, state, reward=0.0):
        self.state = state
        self.reward = reward
        self.response = ""

class JerichoMetaEnv(BaseEnv):
    def __init__(self, 
                 meta_cfg: Dict, 
                 actor_cls: Type, 
                 actor_args: Dict, 
                 log=True,
                 **game_cfg): # Remaining fields become `game_cfg` (rom_path, seed, etc.).
        """
        Args:
            meta_cfg: Meta-loop config such as `max_episodes`.
            actor_cls: Actor class, e.g. `MemoryAgent`.
            actor_args: Initialization args for the actor, e.g. `llm_model`.
            **game_cfg: Per-game task config produced by `prepare_data`.
        """
        # 1. Store configuration.
        self.meta_cfg = meta_cfg
        self.game_cfg = game_cfg
        
        # Extract game-specific parameters.
        self.rom_path = game_cfg.get("rom_path")
        self.base_seed = game_cfg.get("seed")
        self.env_step_limit = meta_cfg.get("env_step_limit", 50) # Per-episode step limit set by the meta loop.
        self.max_episodes = meta_cfg.get("max_episodes", 10)
        self.feedback_history = []
        
        # 2. Instantiate the actor dynamically.
        # `actor_args` is a dict, so wrap it if the actor expects an object-like container.
        
        # Instantiate the actor.
        # The initial prompt could also be stored in `meta_cfg`.
        args_obj = SimpleNamespace(**actor_args)
        self.actor = actor_cls(args=args_obj, guiding_prompt="Initialize...")
        
        self.current_episode_idx = 0
        self.best_score = -float('inf')
        self.log = log

    def reset(self) -> Tuple[str, Dict]:
        self.current_episode_idx = 0
        self.best_score = -float('inf')
        
        # Initial guiding prompt.
        self.feedback_history = []
        initial_prompt = self.meta_cfg.get("initial_prompt", "Explore and maximize score.")
        
        trajectory_log, score, info = self._run_full_game_episode(initial_prompt)
        
        self.best_score = max(self.best_score, score)
        return trajectory_log, {"score": score, "raw_info": info, "termination_reason":info["termination_reason"]}

    def step(self, action: str) -> Tuple[str, float, bool, Dict]:
        # `action` is the new prompt or feedback generated by the meta agent.
        new_feedback = str(action).strip()
        if new_feedback:
            self.feedback_history = [new_feedback]
        self.current_episode_idx += 1
        guiding_feedbacks = ""
        for i, fb in enumerate(self.feedback_history):
            guiding_feedbacks += f"{i+1}. {fb}\n"
        trajectory_log, score, info = self._run_full_game_episode(guiding_feedbacks)
        reward = float(score)
        done = self.current_episode_idx >= self.max_episodes
        
        self.best_score = max(self.best_score, score)
        info["best_score"] = self.best_score
        
        return trajectory_log, reward, done, info

    def _run_full_game_episode(self, guiding_prompt: str) -> Tuple[str, int, Dict]:
        pid = os.getpid()
        tid = threading.get_ident()
        now = datetime.datetime.now().strftime("%H:%M:%S")
        if self.log:
            colorful_print(f"🚀 [PID: {pid}] [Thread {tid}] START Episode {self.current_episode_idx}", "green")
        # colorful_print(f"🚀 [PID: {pid}] [Thread {tid}] START Episode {self.current_episode_idx}", "green")
        # Update the actor prompt.
        self.actor.guiding_prompt = guiding_prompt
        self.actor.start_episode() 

        # Initialize the environment with a fixed seed.
        env = JerichoEnv(
            rom_path=self.rom_path,
            seed=self.base_seed, 
            step_limit=self.env_step_limit + 1,
        )
        
        ob, info = env.reset()
        score = info['score']
        
        traj_buffer = io.StringIO()
        traj_buffer.write(f"Episode: {self.current_episode_idx}\n")
        traj_buffer.write(f"Guiding Prompt: {guiding_prompt}\n")
        traj_buffer.write("--- START GAME ---\n")
        
        done = False
        final_score = score
        prev_obs = None

        for step in range(self.env_step_limit):
            state_node = StateNode(state=ob)
            # Let the actor choose an action.
            action_str, _ = self.actor.generate_action(state_node)
            current_obs_str = ob.strip()
            if prev_obs and current_obs_str == prev_obs:
                display_obs = "(Same as previous step)"
            else:
                display_obs = current_obs_str
            prev_obs = current_obs_str
            traj_buffer.write(f"\n[STEP {step}]\n[OBS]: {display_obs}\n[ACTION]: {action_str}\n")
            
            ob, reward, done, info = env.step(action_str)
            score = info['score']
            traj_buffer.write(f"[REWARD]: {reward}\n")
            traj_buffer.write(f"[CUM_REWARD]: {score}\n")
            
            final_score = score
            if done:
                traj_buffer.write(f"\n[FINAL_OBS]: {ob.strip()}\n")
                traj_buffer.write(f"\nGame finished at step {step}. Final score: {score}\n")
                break
        termination_reason = "TRUNCATION" if not done else "DONE"
        info["termination_reason"] = termination_reason
        if not done:
            traj_buffer.write(f"\n[FINAL_OBS]: {ob.strip()}\n")
            traj_buffer.write(f"\nStep limit ({self.env_step_limit}) reached. Final score: {score}\n")
             
        env.close()
        traj_log = traj_buffer.getvalue()
        now_end = datetime.datetime.now().strftime("%H:%M:%S")
        if self.log:
            colorful_print(f"Episode {self.current_episode_idx} Trajectory log: {traj_log}", "yellow")
            colorful_print(f"Episode {self.current_episode_idx} termination_reason: {termination_reason} score: {final_score}", "green")
        # colorful_print(f"[{now_end}] [Thread {tid}] 🔴 END Episode {self.current_episode_idx}","red")
        # breakpoint()
        return traj_log, final_score, info

    @staticmethod
    def from_dict(env_args: Dict):
        # 1. Copy the dict so `pop` does not mutate a shared object.
        args = env_args.copy()

        # 2. Extract the core meta-loop components.
        meta_cfg = args.pop("meta_cfg")
        actor_cls = args.pop("actor_cls")
        actor_args = args.pop("actor_args")

        # 3. The remaining fields belong to the concrete game config.
        # Pass them through via `**kwargs`.
        return JerichoMetaEnv(
            meta_cfg=meta_cfg,
            actor_cls=actor_cls,
            actor_args=actor_args,
            **args  # corresponds to **game_cfg in __init__
        )
